version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_USER}
      POSTGRES_DB: ${DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORTS}

volumes:
  db_data: {}